shared: &shared
  - ".github/**"
  - "build-scripts/**"
docker:
  - *shared
  - ".dockerignore"
  - Dockerfile
rust: &rust
  - *shared
  - "**/*.toml"
  - ".cargo/**"
  - "crates/**"
  - Cargo.lock
typescript:
  - *shared
  - "**/*.ts"
  - "front-end/**"
  - "package.json"
  - "pnpm-lock.yaml"
  - "pnpm-workspace.yaml"
  - "tsconfig.json"
# the package installs both files, see `license-file` and `assets` in `[package.metadata.deb]`
deb:
  - *rust
  - LICENSE
  - README.md
