services:
  postgres:
    image: postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/db-data/:/var/lib/postgresql/

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:40fa840c5bb7c8463957f1255b01283732c2d8c9396a956d180f8e6c296753b3
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/pgadmin-data/:/var/lib/pgadmin/
    post_start:
      - command: chown --recursive 5050:0 /var/lib/pgadmin/
        user: root

networks:
  postgres-network:
    driver: bridge
