services:
  postgres:
    image: postgres:18.4@sha256:775a0820dd34e907ec63277e388d145056d427548e461d7953a070edb5de3a3a
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/db-data/:/var/lib/postgresql/

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:cefc4cc6b7d9d71a9e81e76fb9d7e14038ab5661b539a190eea1b63fa612589a
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/pgadmin-data/:/var/lib/pgadmin/
    post_start:
      - command: chown --recursive 5050:0 /var/lib/pgadmin/
        user: root

networks:
  postgres-network:
    driver: bridge
