services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/vscode/
    depends_on:
      - postgres
    network_mode: service:postgres
    command: sleep infinity

  postgres:
    image: postgres:18.4@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ../init-db/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
