services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/vscode/
    depends_on:
      - postgres
    network_mode: service:postgres
    command: sleep infinity

  postgres:
    image: postgres:18.3@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ../init-db/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
