services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace/vscode/
    depends_on:
      - postgres
    network_mode: service:postgres
    command: sleep infinity

  postgres:
    image: postgres:18.4@sha256:f7ce845ee6873dd84be93c9828fe0d1fab0f9707dc9ac569694657398b290bce
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ../init-db/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
